### ISSUE TITLE
How to invoke QueryExecutionUtils.queryAll(...)?

### ISSUE THREAD

**Issue by selo-ecube** [commercetools/commercetools-jvm-sdk#1182]
We're looking for a generic way to obtain e.g. all ProductTypes. We previously used

```
protected PagedQueryResult<ProductType> getProductTypes() {
    return sphereClient.executeBlocking(ProductTypeQuery.of().withLimit(100));
}
```
which will certainly only work for up to 100 product types.

Thanks to Nikolaus, we found QueryExecutionUtils and tried to use it:

```
protected PagedQueryResult<ProductType> getProductTypes() {
    return QueryExecutionUtils.queryAll(sphereClient, ProductTypeQuery.of());
}
```

but ProductTypeQuery cannot be provided as argument, QueryDsl<T,C> is required. I cannot see quickly why ProductTypeQuery does not satisfy that constraint.

How is QueryExecutionUtils to be used in order to query all ProductTypes?

**Comment by schleichardt** [comment]
[QueryExecutionUtils#queryAll](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/queries/QueryExecutionUtils.html#queryAll-io.sphere.sdk.client.SphereClient-io.sphere.sdk.queries.QueryDsl-) is returning a `CompletionStage<List<T>>`, you get the compile error because the result type of the method is not matching.

Here is an example for Categories:
http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/meta/CategoryDocumentation.html#read-categories
