### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by kaka89** [commercetools/commercetools-jvm-sdk#1258]
Hi,
why this sdk always build failed?

**Comment by schleichardt** [comment]
The source of truth if the JVM SDK can be released is an internal TeamCity build which is kept stable. The cool thing about that is that new commercetools platform versions are checked with the current JVM SDK version if code is backwards compatible.

There are a lot of sources why the build of an integration tool can be red:

* we run mostly integration tests (more than thousand), if one of them fails because of a connection problem, timeout, eventual consistency in elastic search then the whole build will fail
* we are currently refactoring and improving like generating more classes instead of writing them
* we switched to another commercetools project in the US datacenter and I had one configuration wrong so the tests failed in this build environment
* an improvement in elastic search usage algorithms causes some roundings to change so the tests failed

To conclude a lot of false negative test results appeared in travis. I consider the JVM SDK as a very reliable tool which is heavily tested.
