### ISSUE TITLE
Change the customerId of an Order/a OrderFromCartDraft

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-jvm-sdk#1272]
We have a B2B scenario in our shop using sunrise/commercetools jvm sdk. This results in the following requirement:

Multiple shop user/accounts can be connected to a customer. Each shop user owns a cart. 
If he follows the checkout process, a new order will be created from the cart - but the order needs to belong to the customer (not to the shop user).

Therefore we would like to assign a customerId to the order different from the one which is set in the cart. This is impossible for now as there is no UpdateAction for order regarding this. It's also not possible to set the customerId in the OrderFromCartDraft.

How are the chances to add this option? If not, what are the cons?

Thanks in advance.

**Comment by schleichardt** [comment]
For now I see only the possibility to update the customer ID in the cart (http://dev.commercetools.com/http-api-projects-carts.html#set-customer-id) before creating the order.

Be aware that the product prices can depend on the customer so changing the customer may results in `PriceChanged` error or `DiscountCodeNonApplicable` (http://dev.commercetools.com/http-api-errors.html#bad-request-3) when creating the order.

Since changing the customer ID in the order is not an SDK feature, I can't help you directly, you may open a support request: https://sphere.atlassian.net/servicedesk/customer/portal/1

**Comment by fhaertig** [comment]
Thanks. Just as a note, changing the customerId in the cart is not an option as it belongs to the user and would lead to an extensive error handling (e.g. if payment fails etc.).

**Comment by lauraluiz** [comment]
@fhaertig just a question, instead of having a cart belonging to the shop user and the corresponding order to the customer (shop user's cart -> customer's order), would it be possible to clone the cart and then assign the customer to this new cart and reference the shop user's cart from here? This cart could be then converted into an order (shop user's cart -> customer's cart (copy) -> customer's order).

Of course this technique leaves the shop user's cart open for change, which is very likely undesirable. In any case I would agree that you should better expose your use case to support to find a solution within the platform, as there is not much we can help from the SDK.

**Comment by fhaertig** [comment]
Cloning the cart is possible but not very desirable since this would mean overhead like "finishing" both carts, handling mini-cart etc, too.
In a support call with @nkuehn, we agreed to use the following solution:
The cart belongs to the shopuser, the order belongs to the b2b customer. Therefore, we first handle any payment and if successful, we finally assign the cart to the b2b customer just before making the OrderFromCart call. No user interaction is allowed in between. The Order also gets a custom field to track the issuing shopuser. 

Note that this is only possible as we are not using the commercetools price calculation and the inventory functionality.

**Comment by lauraluiz** [comment]
Thanks for sharing the solution, which might help others with the same requirements as your project.
