### ISSUE TITLE
Add ChangeInputHint update action for AttributeDefinition

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#1424]
We should add support for the new `ChangeInputHint` attribute definition update action. For documentation please take a look at our github dev.commercetools.com repository under CTP-588.

**Comment by katmatt** [comment]
We should try to generate this update action with our update action code generator and then replace all other simple attribute definition update actions with generated ones. 
And we extended our update action code generator so that you now can exclude properties from the code generation by adding the new `HasNoUpdateAction` annotation.

**Comment by ccsalazarr-commercetools** [comment]
@katmatt I think this particular case is not supported yet by our code generator. I made the change to create update actions for Enum variables, but in this case, besides the enum value, it is required also the attribute name to execute the update action. 

and I think this `ChangeInputHint` should extend from `UpdateActionImpl<ProductType>` instead of `UpdateActionImpl<AttributeDefinition>`.

If I am not clear, we could check it the next week. :)

**Comment by katmatt** [comment]
@ccsalazarr-commercetools After taking a closer look at the update actions for `AttributeDefinition`, I realized that our SDK is missing a lot of update actions for `AttributeDefinition` (see #1435). 

 I would suggest to push your changes to support enums in our update action code generator to a different branch. And we then should just manually create this update action.
