### ISSUE TITLE
Switch to new platform uris

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-jvm-sdk#2007]
WE should switch our default platform uris to the new ones. Additionally we could deprecate any method which uses the default uris to encourage our users to explicitly set them in their code.

**Comment by nkuehn** [comment]
Congratulations, you were faster than me (I'm just walking through all OSS repositories to annoy our teams with the topic).   Here's the text I put into the other repos:
----

### Description

To improve the developer experience and easen our support and training burden all existing references to  `*.sphere.io` and `.commercetools.co`  host names should be removed in favor of not defaulting to a specific region (a common complaint of US and AWS customers is that EU is defaulted everywhere) or, if needed for backwards compatibility, be replaced with the new `*.europe-west1.gcp.commercetools.com` notation. 

### Expected Behavior

full text search over the repository for ".sphere.io"  and ".commercetools.co" should yield zero results

### Context

https://docs.commercetools.com/release-notes#releases-2020-02-03-aws-and-new-hostnames

**Comment by katmatt** [comment]
Closed by https://github.com/commercetools/commercetools-jvm-sdk/pull/2010
